acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name='delete'),
    path('chpass/', views.chpass, name='chpass')
]

book/urls.py
from django.urls import path
from . import views

app_name='book'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('tts/', include('tts.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name='vote'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<tpk>', views.detail, name='detail'),
    path('vote/<tpk>', views.vote, name='vote'),
    path('cancle/<tpk>', views.cancel, name='cancel'),
    path('create/', views.create, name='create')
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='maker')
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name='voter')

    def __str__(self):
        return self.subject

class Choice(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    pic = models.ImageField(upload_to='vote')
    content = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.top}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice

# Create your views here.
def index(request):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(request, 'vote/index.html', context)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(request, 'vote/detail.html', context)

def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get('cho')
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect('vote:detail', tpk)

def cancel(request,tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(request.user)
    u.choice_set.get(top=t).choicer.remove(u)
    return redirect('vote:detail', tpk)

def create(request):
    if request.method == "POST":
        s = request.POST.get("top")
        c = request.POST.get("con")
        
        t = Topic(subject=s, content=c, maker=request.user)
        t.save()
        cn = request.POST.getlist("cname")
        cp = request.FILES.getlist("cpic")
        cc = request.POST.getlist("ccom")

        for n,p,c in zip(cn, cp, cc):
            Choice(top=t, name=n, pic=p, content=c).save()
        return redirect("vote:index")
    return render(request, 'vote/create.html')

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-5 mb-5">
            <h1><b>토픽생성</b></h1>

            <input type="text" name="top" class="form-control mt-5" placeholder="TOPIC 제목을 입력하세요">
            <textarea class="form-control mt-4" name="con" placeholder="TOPIC 에 관해서 간단하게 설명해주세요" style="height: 150px;"></textarea>

            <div class="text-end mt-4">
                <button class="btn btn-secondary" type="button" onclick="makesel()">보기생성</button>
                <button class="btn btn-dark">토픽생성</button>
            </div>

            <div id="here" class="row mt-5">
            </div>
        </div>
    </form>


    <script>
        function makesel(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-lg-4 mt-5");
            n.innerHTML = '<input type="text" name="cname" class="form-control" placeholder="보기이름입력">\
                <input type="file" name="cpic" class="form-control mt-3 mb-3">\
                <textarea placeholder="보기설명" name="ccom" class="form-control"></textarea>';
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}
    <h1><b>{{ t.subject }}</b></h1>
    <div class="mt-5 row">
        <div class="col-sm-9">
            <textarea class="form-control" disabled style="height: 200px;">{{ t.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="text-center mt-4"><h4>Created by <b>{{ t.maker }}</b></h4></div>
        </div>
    </div>

    <hr>


    {% if user in t.voter.all %}
        <div class="row mt-5">
            {% for i in cset %}
                <div class="col-lg-4 text-center">
                    <div class="progress mb-4">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%</div>
                    </div>
                    <img src="{{ i.pic.url }}" width="100%">
                    <h4 class="mt-3"><b>{{ i.name }}</b></h4>
                    <textarea class="form-control" style="font-size: 20px; font-weight: bold;" disabled>{{i.content}}</textarea>
                </div>
            {% endfor %}
        </div>
        <div class="mt-5 text-end">
            <a href="{% url 'vote:cancel' t.id %}" class="btn btn-danger">투표취소</a>
        </div>
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-lg-4 text-center">
                        <input class="form-check-input mb-3" type="radio" name="cho" value="{{ i.id }}">
                        <img src="{{ i.pic.url }}" width="100%">
                        <h4 class="mt-3"><b>{{ i.name }}</b></h4>
                        <textarea class="form-control" style="font-size: 20px; font-weight: bold;" disabled>{{i.content}}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="mt-5 text-end">
                <button class="btn btn-dark">투표하기</button>
            </div>
        </form>
    {% endif %}

    <div class="text-end mt-3">
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#book">
            Bookmark
        </button>
    </div>

    <!-- Modal -->
    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="book" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림창</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="sname" value="[BOARD]::{{b.subject}}">
                        <input type="hidden" name="surl" value="{{ request.path }}">
                        <textarea class="form-control" name="scom" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}

<div class="containder mt-5 mb-5">
    <h1><b>투표소</b></h1><br>

    <div class="text-end">
        <a href="{% url 'vote:create' %}" class="btn btn-primary btn-lg">토픽생성</a>
    </div>
    <div class="row">
        {% for i in tset %}
            <div class="col-sm-4 mt-5 text-center">
                <div class="card">
                    <img src="{{i.maker.getpic}}" class="card-img-top" title="{{user}}">
                    <div class="card-body">
                        <h5 class="card-title"><b>{{i.subject}}</b></h5>
                        <p class="card-text">{{i.content}}</p>
                        <a href="{% url 'vote:detail' i.id %}" class="btn btn-primary">
                            {% if user in i.voter.all %} 결과보기 {% else %} 투표하기 {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    

</div>

{% endblock %}