acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name='delete'),
    path('chpass/', views.chpass, name='chpass')
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<bpk>', views.detail, name='detail'),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('creply/<bpk>', views.creply, name='creply'),
    path('dreply/<bpk>/<rpk>', views.dreply, name='dreply'),
    path('likey/<bpk>', views.likey, name='likey')
]

book/urls.py
from django.urls import path
from . import views

app_name='book'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('tts/', include('tts.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='writer')
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name='likey')

    def __str__(self):
        return f"{self.writer}의 {self.subject} 게시글"

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board} 의 {self.replyer} 가 남긴 댓글"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
import googletrans
from googletrans import Translator
from django.contrib import messages

# Create your views here.
def index(request):
    cate = request.GET.get('cate', "")
    kw = request.GET.get('kw', "")
    pg = request.GET.get('page', 1)

    if kw:
        if cate == 'sub':
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == 'wri':
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u) #중요
            except:
                b = Board.objects.none()
        elif cate == 'con':
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.none()
            # 메시지
    else:
        b = Board.objects.all()

    b = b.order_by('pubdate')

    pag = Paginator(b, 3)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw
    }
    return render(request, 'board/index.html', context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b" : b,
        "rset" : r
    }
    return render(request, 'board/detail.html', context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == request.user:
        b.delete()
    else:
        messages.warning(request, '올바른 접근이 아닙니다.')
    return redirect('board:index')

def create(request):
    if request.method == "POST":
        s = request.POST.get('sub')
        c = request.POST.get('con')
        Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
        return redirect('board:index')
    return render(request, 'board/create.html')

def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if request.user != b.writer:
        # 메시지!
        return redirect('board:index')

    if request.method == "POST":
        s = request.POST.get('sub')
        c = request.POST.get('con')
        b.subject, b.content = s, c
        b.save()
        return redirect("board:detail", bpk)

    context = {
        "b" : b
    }
    return render(request, 'board/update.html', context)

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get('com')
    Reply(board=b, comment=c, replyer=request.user).save()
    return redirect('board:detail', bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    else:
        pass # 경고
    return redirect('board:detail', bpk)

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    if not request.user in b.likey.all():
        b.likey.add(request.user)
        return redirect('board:detail', bpk)
    else:
        b.likey.remove(request.user)
        return redirect('board:detail', bpk)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>게시글 생성</b></h1>

    <form method="post" name="createForm">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" class="form-control" name="sub"><br>
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" value="{{ user }}" disabled><br>
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" style="height: 150px;" name="con"></textarea><br>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark" type="button" onclick="check()">생성</button>
        </div>
    </form>

    <script>
        function check() {
            cf = document.createForm;
            if(!cf.sub.value){
                alert("제목을 입력해주세요.")
            }else if(cf.con.value.length < 10){
                alert("본문은 최소 10글자 이상이어야 합니다.")
            }else{
                cf.submit();
            }
        }
    </script>

{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}

    <h1><b>{{b.subject}}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height:200px" disabled>{{b.content}}</textarea>
        </div>
        <div class="col-sm-3 text-center">
            <img src="{{b.writer.getpic}}" width="100%">
            <div class="mt-2">
                <h4>written by <b>{{b.writer}}</b></h4>
            </div>
            <div class="mt-2 text-end">
                {{b.pubdate | date:'Y년 n월 j일 H:i'}}
            </div>
        </div>
        <div class="text-end mt-5">
            <a href="{% url 'board:index' %}"><button class="btn btn-dark">글목록</button></a>
            {% if user == b.writer %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">글수정</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    글삭제
                </button>
            {% endif %}
        </div>

        <div class="text-end mt-4 mb-4">
            {% if request.user in b.likey.all %}
                <a href="{% url 'board:likey' b.id %}" class="btn btn-primary btn-sm">👍x</a>
            {% else %}
                <a href="{% url 'board:likey' b.id %}" class="btn btn-primary btn-sm">👍</a>
                
            {% endif %}
            <div class="text-end">
                {% if b.likey.count == 0 %}
                {% else %}
                    {% for i in b.likey.all %}
                        <img src="{{i.getpic}}" width="50px">
                    {% endfor %}
                    님이 좋아합니다!
                {% endif %}

                <br><br>
                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#book">
                    Bookmark
                </button>

            </div>
        </div>

        <hr>

        <div class="text-center" style="width: 100%;">
            {% for i in rset %}
                <div class="row mt-5">
                    <div class="col-sm-3">
                        <img src="{{i.replyer.getpic}}" width="100%">
                        <div class="mt-3">
                            <b>작성자</b> : {{i.replyer}}
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <textarea class="form-control" style="height: 150px" disabled>{{i.comment}}</textarea>
                        <div class="mt-3 text-end">
                            {% if i.replyer == user %}
                                <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger">댓글 삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="mt-4 text-center">
                    <h5><b>---------- 댓글을 달아주세요. ----------</b></h5>
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row mt-3">
                <div class="col-sm-10">
                    <input class="form-control text-end" name="com" placeholder="댓글을 입력하세요.">
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-primary" style="width: 100%;">댓글 생성</button>
                </div>
            </div>
        </form>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림창</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    '{{b.subject}}' 다음 게시글을 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}"  class="btn btn-primary">삭제</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="book" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림창</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="sname" value="[BOARD]::{{b.subject}}">
                        <input type="hidden" name="surl" value="{{ request.path }}">
                        <textarea class="form-control" name="scom" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

{% load mathfilters %}

    <div class="text-center">
        <h1><b>게시판</b></h1>
    </div>

    <div class="text-end">
        <a href="{% url 'board:create' %}" class="btn btn-warning"><b>게시글생성</b></a>
    </div>

    <table class="table table-hover mt-4">
        <thead>
            <tr class="table-warning text-center">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% for i in bset %}
                <tr class="text-center">
                    <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                    <td><a class="sub" href="{% url 'board:detail' i.id %}">{{i.subject}}</a></td>
                    <td>{{i.content|truncatewords:10}}</td>
                    <td>{{i.writer}}</td>
                    <td>{{i.likey.count}}</td>
                </tr>
            {% empty %}
            <tr>
                <th colspan="5" class="text-center">
                    {% if kw %}
                        검색 결과가 없습니다.
                    {% else %}
                        게시글이 존재하지 않습니다.
                    {% endif %}
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <nav aria-label="Page navigation example" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}
            

            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:5 >= i and i >= bset.number|sub:4 %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
        </ul>
    </nav>

    <br>
    <form>
        <div class="row mt-4">
            <div class="col-sm-2">
                <select class="form-select" aria-label="Default select example" name="cate">
                    <option selected>Open this select menu</option>
                    <option value="sub" {% if cate == 'sub' %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == 'wri' %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == 'con' %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input class="form-select" type="text" name="kw" value="{{kw}}" size="70" placeholder="검색하실 내용을 입력해주세요.">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-success" style="width: 100%;">search</button>
            </div>
            <div class="col-sm-1">
                <a href="{% url 'board:index' %}" class="btn btn-secondary" style="width: 100%;">리셋</a>
            </div>
        </div>
    </form>

    <style>
        .sub {
            text-decoration: none;
            color:rgb(0, 0, 0);
            font-weight: bold;
        }
        .sub:hover{
            color:red;
        }
    </style>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" class="form-control" value="{{b.subject}}" name="sub">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" style="height: 150px;" name="con">{{b.content}}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div>
    </form>

{% endblock %}